<?xml version="1.0"?>
<package format="3">
  <name>rangerwm_policy</name>
  <version>0.1.0</version>
  <description>Policy inference node.</description>
  <maintainer email="dev@example.com">rangerwm</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rangerwm_msgs</depend>
  <export><build_type>ament_python</build_type></export>
</package>
