<?xml version="1.0"?>
<package format="3">
  <name>rangerwm_data_recorder</name>
  <version>0.1.0</version>
  <description>rosbag aligned index recorder.</description>
  <maintainer email="dev@example.com">rangerwm</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>message_filters</depend>
  <export><build_type>ament_python</build_type></export>
</package>
