#!/usr/bin/env python3
"""
Offline rosbag analysis tool.

Computes navigation metrics from pre-recorded rosbag files.
Usage:
  bag_analyzer.py /path/to/bag_directory --output results.csv
"""
import argparse
import csv
import math
import os
import sys
from collections import defaultdict

import numpy as np


class BagAnalyzer:
    """Analyzes metrics CSV files generated by metrics_logger."""

    def __init__(self, metrics_dir, output_path):
        self.metrics_dir = metrics_dir
        self.output_path = output_path
        self.results = []

    def analyze_all(self):
        """Process all metrics_*.csv files in the directory."""
        csv_files = sorted([
            f for f in os.listdir(self.metrics_dir)
            if f.startswith('metrics_') and f.endswith('.csv')
        ])
        if not csv_files:
            print(f'No metrics_*.csv files found in {self.metrics_dir}')
            return

        for fname in csv_files:
            path = os.path.join(self.metrics_dir, fname)
            result = self._analyze_one(path)
            result['file'] = fname
            self.results.append(result)
            print(f'  {fname}: {result}')

        self._write_summary()

    def _analyze_one(self, path):
        rows = []
        with open(path, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                rows.append(row)

        if not rows:
            return {}

        # Parse numeric fields
        pos_x = [float(r['pos_x']) for r in rows]
        pos_y = [float(r['pos_y']) for r in rows]
        vel_x = [float(r['vel_x']) for r in rows]
        vel_y = [float(r['vel_y']) for r in rows]
        vel_wz = [float(r['vel_wz']) for r in rows]
        path_len = float(rows[-1]['path_length'])
        replan_count = int(rows[-1]['replan_count'])
        estop_count = int(rows[-1]['estop_count'])
        failure_count = int(rows[-1]['failure_count'])

        # Derived metrics
        total_dist = max(path_len, math.hypot(pos_x[-1] - pos_x[0], pos_y[-1] - pos_y[0]))
        speeds = [math.hypot(vx, vy) for vx, vy in zip(vel_x, vel_y)]
        avg_speed = float(np.mean(speeds))
        max_speed = float(np.max(speeds))

        # Time
        if rows:
            t0 = float(rows[0]['timestamp'])
            t1 = float(rows[-1]['timestamp'])
            duration = t1 - t0
        else:
            duration = 0.0

        # Smoothness
        speed_diffs = [abs(speeds[i] - speeds[i-1]) for i in range(1, len(speeds))]
        smoothness = float(np.mean(speed_diffs)) if speed_diffs else 0.0

        return {
            'duration_s': f'{duration:.1f}',
            'path_length_m': f'{total_dist:.2f}',
            'avg_speed_ms': f'{avg_speed:.2f}',
            'max_speed_ms': f'{max_speed:.2f}',
            'replan_count': replan_count,
            'estop_count': estop_count,
            'failure_count': failure_count,
            'smoothness': f'{smoothness:.4f}',
        }

    def _write_summary(self):
        if not self.results:
            return
        fieldnames = list(self.results[0].keys())
        with open(self.output_path, 'w', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(self.results)
        print(f'\nSummary written to {self.output_path}')


def main():
    parser = argparse.ArgumentParser(description='Analyze navigation metrics from rosbag CSV exports')
    parser.add_argument('metrics_dir', help='Directory containing metrics_*.csv files')
    parser.add_argument('--output', '-o', default='nav_summary.csv', help='Output CSV path')
    args = parser.parse_args()

    if not os.path.isdir(args.metrics_dir):
        print(f'ERROR: {args.metrics_dir} is not a directory')
        sys.exit(1)

    analyzer = BagAnalyzer(args.metrics_dir, args.output)
    analyzer.analyze_all()


if __name__ == '__main__':
    main()
